### ISSUE TITLE
Berechtigungen für Top of Information Store werden nicht ausgelesen

### ISSUE THREAD

**Issue by michaelbast** [Apoc70/Get-MailboxPermissionReport#3]
Hi Thomas,

mir ist aufgefallen, dass die Berechtigungen für den Top of Information Store der Postfächer nicht ausgelesen werden.

Das Problem ist, dass Get-MailboxFolderStatistics den Ordner '/Top of Information Store' ausgibt. Nach Umwandlung (replace) erhält Get-MailboxFolderPermission dann 'Mailbox:\Top of Information Store' als Eingabe. Das Format müsste aber Mailbox:\ sein.

Ich habe in der Zeile unter '# Featch folders' folgendes eingefügt:
... | ForEach-Object{$_.replace('/Top of Information Store','\ ')} | ForEach-Object...

Somit klappt das Auslesen.

LG
Micha

**Comment by Apoc70** [comment]
Hallo Micha,
danke für das Feedback. Möchtest du hierzu einen Pull-Request einstellen? Ansonsten ändere ich das heute Abend im Quellcode.
Beste Grüße,
Thomas

**Comment by michaelbast** [comment]
Hi Thomas,
ich bin noch Anfänger auf GitHub. Ich hoffe ich habe den Pull-Request richtig erstellt.

LG
Micha

**Comment by Apoc70** [comment]
Alles bestens. :-)
